FROM ubuntu:bionic

RUN apt-get update && apt-get install -y  \
automake \
libtool \
make \
gcc \
pkg-config \
git 

WORKDIR yara

CMD sh -c "./bootstrap.sh && ./configure && make && cp -R /yara /public && ls -la && ls -la /public"
